# -*- coding: utf-8 -*-
"""MLFINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PkLRdm2-CBJ8MVGira5tH2wjpdvNZ7xo
"""

df = pd.read_csv("BK_18v1.csv.zip", compression='zip')

from google.colab import files

# Save dataframe as CSV
df.to_csv('preprocessed_BK_dataset.csv', index=False)

# Download file
files.download('preprocessed_BK_dataset.csv')

from google.colab import files
files.download('preprocessed_BK_dataset.csv')

df = pd.read_csv("BK_18v1.csv.zip", compression='zip', low_memory=False)

from google.colab import files

# Save dataframe as CSV
df.to_csv('preprocessed_BK_dataset.csv', index=False)

# Download file
files.download('preprocessed_BK_dataset.csv')

import pandas as pd

df = pd.read_csv('preprocessed_BK_dataset.csv')

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('preprocessed_BK_dataset.csv')
df.head()

!unzip BK_18v1.csv.zip

!ls

import pandas as pd

df = pd.read_csv('BK_18v1.csv')
df.head()

df.to_csv('preprocessed_BK_dataset.csv', index=False)

from google.colab import files
files.download('preprocessed_BK_dataset.csv')

print("Shape:", df.shape)
df.head()
df.info()
df.describe()

df.isnull().sum().sort_values(ascending=False).head(20)

threshold = 0.5   # 50% missing
df = df.loc[:, df.isnull().mean() < threshold]

print("Shape after dropping empty columns:", df.shape)

import numpy as np

num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df = df.drop_duplicates()
print("Final Shape:", df.shape)

target = "LandUse"

X = df.drop(columns=[target])
y = df[target]

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in cat_cols:
    if df[col].nunique() < 20:
        df[col] = le.fit_transform(df[col])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

from sklearn.model_selection import train_test_split

X = df.drop(columns=[target])
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape, X_test.shape)

from google.colab import files
files.download("preprocessed_BK_dataset.csv")

print("Missing values:", df.isnull().sum().sum())
print("Duplicates:", df.duplicated().sum())
print("Final Shape:", df.shape)

target = "LandUse"   # or ZipCode or any column you want

X = df.drop(columns=[target])
y = df[target]

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

simple_results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    simple_results[name] = accuracy_score(y_test, y_pred)

simple_results

df.select_dtypes(include='object').columns

df.to_csv("preprocessed_BK_dataset.csv", index=False)

df.select_dtypes(include='object').columns

df = pd.get_dummies(df, drop_first=True)

import pandas as pd

df = pd.get_dummies(df, drop_first=True)

import pandas as pd

df = pd.get_dummies(df, drop_first=True)

import pandas as pd

df = pd.read_csv("BK_18v1.csv.zip", compression='zip', low_memory=False)

df = pd.get_dummies(df, drop_first=True)

df = pd.get_dummies(df, drop_first=True)

import pandas as pd

df = pd.read_csv("BK_18v1.csv.zip", compression='zip', low_memory=False)

df = pd.get_dummies(df, drop_first=True)

import pandas as pd

df = pd.read_csv("BK_18v1.csv.zip", compression='zip', low_memory=False)

df = pd.get_dummies(df, drop_first=True)

import pandas as pd

df = pd.read_csv("BK_18v1.csv.zip", compression="zip", low_memory=False)

# Select only categorical columns with small unique values
cat_cols = df.select_dtypes(include="object").columns

for col in cat_cols:
    if df[col].nunique() < 20:   # only small categories
        df[col] = df[col].astype("category").cat.codes

print("Selective encoding completed")

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files

files.download('preprocessed_civic_issues_dataset.csv')

# Install required library
!pip install mlxtend

# Import libraries
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Step 1: Create dataset (transactions)
transactions = [
    ['Garbage', 'Urban', 'High', 'Open'],
    ['Pothole', 'Urban', 'Medium', 'Closed'],
    ['Water Leakage', 'Rural', 'High', 'Open'],
    ['Streetlight', 'Urban', 'Low', 'Resolved'],
    ['Garbage', 'Rural', 'High', 'Open'],
    ['Pothole', 'Rural', 'Medium', 'Open'],
    ['Water Leakage', 'Urban', 'High', 'Closed'],
    ['Streetlight', 'Rural', 'Low', 'Resolved'],
    ['Garbage', 'Urban', 'High', 'Open'],
    ['Pothole', 'Urban', 'Medium', 'Closed']
]

# Step 2: Convert transactions into one-hot encoded DataFrame
te = TransactionEncoder()
te_data = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_data, columns=te.columns_)

print("📊 One-Hot Encoded Data:")
print(df.head())

# Step 3: Apply Apriori Algorithm
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

print("\n📌 Frequent Itemsets:")
print(frequent_itemsets)

# Step 4: Generate Association Rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)

print("\n🔗 Association Rules:")
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])

# Install required libraries
!pip install tensorflow scikit-learn pandas

# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create same dataset (like Apriori)
data = [
    ['Garbage', 'Urban', 'High', 'Open'],
    ['Pothole', 'Urban', 'Medium', 'Closed'],
    ['Water Leakage', 'Rural', 'High', 'Open'],
    ['Streetlight', 'Urban', 'Low', 'Resolved'],
    ['Garbage', 'Rural', 'High', 'Open'],
    ['Pothole', 'Rural', 'Medium', 'Open'],
    ['Water Leakage', 'Urban', 'High', 'Closed'],
    ['Streetlight', 'Rural', 'Low', 'Resolved'],
    ['Garbage', 'Urban', 'High', 'Open'],
    ['Pothole', 'Urban', 'Medium', 'Closed']
]

# Convert to DataFrame
df = pd.DataFrame(data, columns=['Issue', 'Location', 'Priority', 'Status'])

# One-hot encoding
df_encoded = pd.get_dummies(df)

# Split features and target (Predict Priority)
X = df_encoded.drop(columns=['Priority_High', 'Priority_Low', 'Priority_Medium'])
y = df_encoded[['Priority_High', 'Priority_Low', 'Priority_Medium']]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Build Deep Learning Model
model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(X.shape[1],)))
model.add(Dense(12, activation='relu'))
model.add(Dense(3, activation='softmax'))

# Compile model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train model
model.fit(X_train, y_train, epochs=50, batch_size=2, validation_data=(X_test, y_test))

# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print("\nTest Accuracy:", accuracy)

# Predictions
predictions = model.predict(X_test)
print("\nSample Predictions:")
print(predictions[:5])

# Install required library
!pip install scikit-learn

from sklearn.metrics import classification_report
import pandas as pd
import numpy as np

# Convert predictions to labels
y_pred = model.predict(X_test)

# Convert one-hot to class labels
y_pred_labels = np.argmax(y_pred, axis=1)
y_true_labels = np.argmax(y_test.values, axis=1)

# Generate classification report
report = classification_report(
    y_true_labels,
    y_pred_labels,
    target_names=['High', 'Low', 'Medium'],
    output_dict=True
)

# Convert to DataFrame (table format)
report_df = pd.DataFrame(report).transpose()

print("📊 Model Evaluation Table:")
print(report_df)

# Install required libraries
!pip install tensorflow scikit-learn pandas

# Upload dataset
from google.colab import files
uploaded = files.upload()

# Load dataset
import pandas as pd
df = pd.read_csv("civic_preprocessed.csv")

# Split features and target
X = df.drop(columns=['High', 'Medium', 'Low'])
y = df[['High', 'Medium', 'Low']]

# Train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Build Deep Learning Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(X.shape[1],)))
model.add(Dense(12, activation='relu'))
model.add(Dense(3, activation='softmax'))

# Compile model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train model
model.fit(X_train, y_train, epochs=50, batch_size=5, validation_data=(X_test, y_test))

# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

# Predictions
predictions = model.predict(X_test)
print("Sample Predictions:")
print(predictions[:5])

from sklearn.metrics import classification_report
import pandas as pd
import numpy as np

# Predictions
y_pred = model.predict(X_test)

# Convert one-hot to labels
y_pred_labels = np.argmax(y_pred, axis=1)
y_true_labels = np.argmax(y_test.values, axis=1)

# Automatically detect labels present
labels = np.unique(np.concatenate((y_true_labels, y_pred_labels)))

# Generate report safely
report = classification_report(
    y_true_labels,
    y_pred_labels,
    labels=labels,
    output_dict=True
)

# Convert to table
report_df = pd.DataFrame(report).transpose()

print("📊 Model Evaluation Table:")
print(report_df)

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Predictions
y_pred = model.predict(X_test)

# Convert one-hot to labels
y_pred_labels = np.argmax(y_pred, axis=1)
y_true_labels = np.argmax(y_test.values, axis=1)

# Calculate metrics
accuracy = accuracy_score(y_true_labels, y_pred_labels)
precision = precision_score(y_true_labels, y_pred_labels, average='weighted', zero_division=0)
recall = recall_score(y_true_labels, y_pred_labels, average='weighted', zero_division=0)
f1 = f1_score(y_true_labels, y_pred_labels, average='weighted', zero_division=0)

# Create table
performance_df = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-Score"],
    "Value": [accuracy, precision, recall, f1]
})

# Display table
print("\nDeepLearning_Performance")
print(performance_df)

# Install required libraries (run once)
!pip install tensorflow scikit-learn pandas

# Import libraries
import pandas as pd

# Load your dataset (make sure filename matches)
df = pd.read_csv("civic_preprocessed.csv")

# Split features and target
X = df.drop(columns=['High', 'Medium', 'Low'])
y = df[['High', 'Medium', 'Low']]

# Train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Build Deep Learning Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(X.shape[1],)))
model.add(Dense(12, activation='relu'))
model.add(Dense(3, activation='softmax'))

# Compile model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train model
model.fit(X_train, y_train, epochs=50, batch_size=5, validation_data=(X_test, y_test))

# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

# Predictions
predictions = model.predict(X_test)
print("Sample Predictions:")
print(predictions[:5])

df.select_dtypes(include="object").columns

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

remaining_cols = df.select_dtypes(include="object").columns

for col in remaining_cols:
    df[col] = le.fit_transform(df[col])

print("All columns are now numeric")

df.info()

target = "LandUse"

X = df.drop(columns=[target])
y = df[target]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

df = df.sample(50000, random_state=42)

target = "LandUse"   # change if your target is different

X = df.drop(columns=[target])
y = df[target]

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

simple_results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    simple_results[name] = accuracy_score(y_test, y_pred)

simple_results

print("Missing values:", df.isnull().sum().sum())

df = df.fillna(df.median(numeric_only=True))

print("Missing values after fix:", df.isnull().sum().sum())

X = df.drop(columns=[target])
y = df[target]

df.isnull().sum().sum()

X = df.drop(columns=[target])
y = df[target]

import numpy as np

# Remove infinite values
df.replace([np.inf, -np.inf], 0, inplace=True)

# Final safety fill
df.fillna(0, inplace=True)

print("NaN:", df.isnull().sum().sum())
print("Inf:", np.isinf(df).sum().sum())

X = df.drop(columns=[target])
y = df[target]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.metrics import accuracy_score

simple_results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    simple_results[name] = accuracy_score(y_test, y_pred)

simple_results

df = df.sample(40000, random_state=42)

X = df.drop(columns=[target])
y = df[target]

from sklearn.model_selection import train_test_split, StratifiedShuffleSplit, cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators=50)
}

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

simple_results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    simple_results[name] = accuracy_score(y_test, y_pred)

sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in sss.split(X, y):
    X_train_s, X_test_s = X.iloc[train_index], X.iloc[test_index]
    y_train_s, y_test_s = y.iloc[train_index], y.iloc[test_index]

stratified_results = {}

for name, model in models.items():
    model.fit(X_train_s, y_train_s)
    y_pred = model.predict(X_test_s)
    stratified_results[name] = accuracy_score(y_test_s, y_pred)

cv_results = {}

for name, model in models.items():
    scores = cross_val_score(model, X, y, cv=5)
    cv_results[name] = scores.mean()

comparison_table = pd.DataFrame({
    "Algorithm": models.keys(),
    "Simple Split Accuracy": simple_results.values(),
    "Stratified Split Accuracy": stratified_results.values(),
    "5-Fold CV Accuracy": cv_results.values()
})

comparison_table = comparison_table.round(4)

comparison_table

df_cluster = df.sample(30000, random_state=42)
print(df_cluster.shape)

X = df_cluster.drop(columns=[target], errors='ignore')

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
kmeans_labels = kmeans.fit_predict(X_scaled)

df_cluster["KMeans_Cluster"] = kmeans_labels

from sklearn.cluster import AgglomerativeClustering

hierarchical = AgglomerativeClustering(n_clusters=3)
hierarchical_labels = hierarchical.fit_predict(X_scaled)

df_cluster["Hierarchical_Cluster"] = hierarchical_labels

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=1.5, min_samples=10)
dbscan_labels = dbscan.fit_predict(X_scaled)

df_cluster["DBSCAN_Cluster"] = dbscan_labels

from sklearn.metrics import silhouette_score

print("KMeans Silhouette:", silhouette_score(X_scaled, kmeans_labels))
print("Hierarchical Silhouette:", silhouette_score(X_scaled, hierarchical_labels))
print("DBSCAN Silhouette:", silhouette_score(X_scaled, dbscan_labels))

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.scatter(X_pca[:,0], X_pca[:,1], c=kmeans_labels)
plt.title("KMeans Clustering")
plt.show()

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Reduce to 2D
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Plot Hierarchical Clusters
plt.figure(figsize=(8,6))
plt.scatter(X_pca[:,0], X_pca[:,1], c=hierarchical_labels)
plt.title("Hierarchical Clustering (PCA Visualization)")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.show()

plt.figure(figsize=(8,6))
plt.scatter(X_pca[:,0], X_pca[:,1], c=dbscan_labels)
plt.title("DBSCAN Clustering (PCA Visualization)")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.show()